
pragma options "--bnd-inbits 5";
pragma options "--bnd-inline-amnt 4";

generator int rec(int x, int y, int z){ /* automatically rewritten */
   int t = ??;
   if(t == 0){
     return x;
   }   
   if(t == 1){
     return y;
   }

   if(t == 2){
     return z;
   }
   int a = rec(x,y,z);
   int b = rec(x,y,z);

   if(t == 3){
     return a * b;
   }

   if(t == 4){
     return a + b;
   } 
   
   return a - b;
}

harness void sketch( int x, int y, int z ){
   assert rec(x,y, z) == (x + x) * (y - z);
}
