#!/bin/sh

# Run the saiger program on a .aig file.
# Assert the result is UNSAT
# This assumes the result should be UNSAT
./utils/aigtoaig -a $1 | ./build/release/saiger -k0 4 -ki 3 > build/`basename $1`.wit
cmp build/`basename $1`.wit utils/unsat.wit

