#!/bin/sh

# Run the aiger program on a .aig file.
# Assert the result is a correct witness.
./utils/aigtoaig -a $1 | ./build/release/aiger -k0 4 -ki 3 > build/`basename $1`.wit
./utils/aigsim -m -c $1 build/`basename $1`.wit

